module

public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch000
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch001
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch002
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch003
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch004
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch005
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch006
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch007
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch008
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch009
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch010
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch011
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch012
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch013
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch014
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch015
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch016
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch017
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch018
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch019
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch020
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch021
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch022
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch023
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch024
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch025
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch026
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch027
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch028
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch029
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch030
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch031
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch032
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch033
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch034
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch035
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch036
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch037
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch038
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch039
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch040
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch041
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch042
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch043
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch044
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch045
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch046
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch047
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch048
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch049
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch050
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch051
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch052
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch053
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch054
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch055
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch056
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch057
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch058
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch059
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch060
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch061
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch062
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch063
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch064
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch065
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch066
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch067
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch068
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch069
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch070
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch071
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch072
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch073
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch074
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch075
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch076
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch077
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch078
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch079
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch080
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch081
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch082
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch083
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch084
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch085
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch086
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch087
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch088
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch089
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch090
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch091
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch092
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch093
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch094
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch095
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch096
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch097
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch098
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch099
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch100
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch101
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch102
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch103
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch104
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch105
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch106
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch107
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch108
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch109
public import BerryEsseen.Certificates.FiniteLowTaylorPanels.Batch110

@[expose] public section

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace FiniteLowTaylorPanels

open BerryEsseen Real MeasureTheory

def allPanels : Array CertifiedLowPanel := #[
  FiniteLowTaylorPanel0_3.certificate, FiniteLowTaylorPanel0_4.certificate, FiniteLowTaylorPanel0_5.certificate, FiniteLowTaylorPanel0_8.certificate, FiniteLowTaylorPanel0_9.certificate,
  FiniteLowTaylorPanel0_13.certificate, FiniteLowTaylorPanel0_14.certificate, FiniteLowTaylorPanel1_2.certificate, FiniteLowTaylorPanel1_3.certificate, FiniteLowTaylorPanel1_4.certificate,
  FiniteLowTaylorPanel1_5.certificate, FiniteLowTaylorPanel1_7.certificate, FiniteLowTaylorPanel1_8.certificate, FiniteLowTaylorPanel2_2.certificate, FiniteLowTaylorPanel2_3.certificate,
  FiniteLowTaylorPanel2_7.certificate, FiniteLowTaylorPanel2_8.certificate, FiniteLowTaylorPanel2_10.certificate, FiniteLowTaylorPanel2_11.certificate, FiniteLowTaylorPanel2_17.certificate,
  FiniteLowTaylorPanel2_18.certificate, FiniteLowTaylorPanel3_2.certificate, FiniteLowTaylorPanel3_3.certificate, FiniteLowTaylorPanel3_4.certificate, FiniteLowTaylorPanel3_8.certificate,
  FiniteLowTaylorPanel3_9.certificate, FiniteLowTaylorPanel3_13.certificate, FiniteLowTaylorPanel3_14.certificate, FiniteLowTaylorPanel4_2.certificate, FiniteLowTaylorPanel4_3.certificate,
  FiniteLowTaylorPanel4_7.certificate, FiniteLowTaylorPanel4_8.certificate, FiniteLowTaylorPanel4_16.certificate, FiniteLowTaylorPanel4_17.certificate, FiniteLowTaylorPanel4_24.certificate,
  FiniteLowTaylorPanel4_25.certificate, FiniteLowTaylorPanel5_2.certificate, FiniteLowTaylorPanel5_3.certificate, FiniteLowTaylorPanel5_4.certificate, FiniteLowTaylorPanel5_8.certificate,
  FiniteLowTaylorPanel5_9.certificate, FiniteLowTaylorPanel5_20.certificate, FiniteLowTaylorPanel5_21.certificate, FiniteLowTaylorPanel6_1.certificate, FiniteLowTaylorPanel6_2.certificate,
  FiniteLowTaylorPanel6_3.certificate, FiniteLowTaylorPanel6_4.certificate, FiniteLowTaylorPanel6_9.certificate, FiniteLowTaylorPanel6_10.certificate, FiniteLowTaylorPanel7_3.certificate,
  FiniteLowTaylorPanel7_4.certificate, FiniteLowTaylorPanel7_5.certificate, FiniteLowTaylorPanel7_6.certificate, FiniteLowTaylorPanel7_11.certificate, FiniteLowTaylorPanel7_12.certificate,
  FiniteLowTaylorPanel8_1.certificate, FiniteLowTaylorPanel8_2.certificate, FiniteLowTaylorPanel8_3.certificate, FiniteLowTaylorPanel8_8.certificate, FiniteLowTaylorPanel8_9.certificate,
  FiniteLowTaylorPanel8_15.certificate, FiniteLowTaylorPanel8_16.certificate, FiniteLowTaylorPanel9_3.certificate, FiniteLowTaylorPanel9_4.certificate, FiniteLowTaylorPanel9_5.certificate,
  FiniteLowTaylorPanel9_6.certificate, FiniteLowTaylorPanel9_9.certificate, FiniteLowTaylorPanel9_10.certificate, FiniteLowTaylorPanel10_4.certificate, FiniteLowTaylorPanel10_5.certificate,
  FiniteLowTaylorPanel10_6.certificate, FiniteLowTaylorPanel10_7.certificate, FiniteLowTaylorPanel10_10.certificate, FiniteLowTaylorPanel10_11.certificate, FiniteLowTaylorPanel11_2.certificate,
  FiniteLowTaylorPanel11_3.certificate, FiniteLowTaylorPanel11_5.certificate, FiniteLowTaylorPanel11_6.certificate, FiniteLowTaylorPanel11_17.certificate, FiniteLowTaylorPanel11_18.certificate,
  FiniteLowTaylorPanel11_23.certificate, FiniteLowTaylorPanel11_24.certificate, FiniteLowTaylorPanel12_2.certificate, FiniteLowTaylorPanel12_3.certificate, FiniteLowTaylorPanel12_5.certificate,
  FiniteLowTaylorPanel12_6.certificate, FiniteLowTaylorPanel12_9.certificate, FiniteLowTaylorPanel12_10.certificate, FiniteLowTaylorPanel13_2.certificate, FiniteLowTaylorPanel13_3.certificate,
  FiniteLowTaylorPanel13_5.certificate, FiniteLowTaylorPanel13_6.certificate, FiniteLowTaylorPanel13_9.certificate, FiniteLowTaylorPanel13_10.certificate, FiniteLowTaylorPanel14_2.certificate,
  FiniteLowTaylorPanel14_3.certificate, FiniteLowTaylorPanel14_4.certificate, FiniteLowTaylorPanel14_10.certificate, FiniteLowTaylorPanel14_11.certificate, FiniteLowTaylorPanel14_22.certificate,
  FiniteLowTaylorPanel14_23.certificate, FiniteLowTaylorPanel15_1.certificate, FiniteLowTaylorPanel15_2.certificate, FiniteLowTaylorPanel15_3.certificate, FiniteLowTaylorPanel15_4.certificate,
  FiniteLowTaylorPanel15_10.certificate, FiniteLowTaylorPanel15_11.certificate, FiniteLowTaylorPanel16_2.certificate, FiniteLowTaylorPanel16_3.certificate, FiniteLowTaylorPanel16_4.certificate,
  FiniteLowTaylorPanel16_5.certificate, FiniteLowTaylorPanel16_9.certificate, FiniteLowTaylorPanel16_10.certificate, FiniteLowTaylorPanel17_1.certificate, FiniteLowTaylorPanel17_2.certificate,
  FiniteLowTaylorPanel17_3.certificate, FiniteLowTaylorPanel17_4.certificate, FiniteLowTaylorPanel17_9.certificate, FiniteLowTaylorPanel17_10.certificate, FiniteLowTaylorPanel18_1.certificate,
  FiniteLowTaylorPanel18_2.certificate, FiniteLowTaylorPanel18_3.certificate, FiniteLowTaylorPanel18_4.certificate, FiniteLowTaylorPanel18_12.certificate, FiniteLowTaylorPanel18_13.certificate,
  FiniteLowTaylorPanel19_2.certificate, FiniteLowTaylorPanel19_3.certificate, FiniteLowTaylorPanel19_4.certificate, FiniteLowTaylorPanel19_5.certificate, FiniteLowTaylorPanel19_12.certificate,
  FiniteLowTaylorPanel19_13.certificate, FiniteLowTaylorPanel20_2.certificate, FiniteLowTaylorPanel20_3.certificate, FiniteLowTaylorPanel20_4.certificate, FiniteLowTaylorPanel20_5.certificate,
  FiniteLowTaylorPanel20_12.certificate, FiniteLowTaylorPanel20_13.certificate, FiniteLowTaylorPanel21_2.certificate, FiniteLowTaylorPanel21_3.certificate, FiniteLowTaylorPanel21_4.certificate,
  FiniteLowTaylorPanel21_5.certificate, FiniteLowTaylorPanel21_11.certificate, FiniteLowTaylorPanel21_12.certificate, FiniteLowTaylorPanel22_4.certificate, FiniteLowTaylorPanel22_5.certificate,
  FiniteLowTaylorPanel22_6.certificate, FiniteLowTaylorPanel22_7.certificate, FiniteLowTaylorPanel22_11.certificate, FiniteLowTaylorPanel22_12.certificate, FiniteLowTaylorPanel23_4.certificate,
  FiniteLowTaylorPanel23_5.certificate, FiniteLowTaylorPanel23_6.certificate, FiniteLowTaylorPanel23_7.certificate, FiniteLowTaylorPanel23_10.certificate, FiniteLowTaylorPanel23_11.certificate,
  FiniteLowTaylorPanel24_2.certificate, FiniteLowTaylorPanel24_3.certificate, FiniteLowTaylorPanel24_4.certificate, FiniteLowTaylorPanel24_7.certificate, FiniteLowTaylorPanel24_8.certificate,
  FiniteLowTaylorPanel24_17.certificate, FiniteLowTaylorPanel24_18.certificate, FiniteLowTaylorPanel25_2.certificate, FiniteLowTaylorPanel25_3.certificate, FiniteLowTaylorPanel25_4.certificate,
  FiniteLowTaylorPanel25_5.certificate, FiniteLowTaylorPanel25_10.certificate, FiniteLowTaylorPanel25_11.certificate, FiniteLowTaylorPanel26_2.certificate, FiniteLowTaylorPanel26_3.certificate,
  FiniteLowTaylorPanel26_4.certificate, FiniteLowTaylorPanel26_5.certificate, FiniteLowTaylorPanel26_10.certificate, FiniteLowTaylorPanel26_11.certificate, FiniteLowTaylorPanel27_2.certificate,
  FiniteLowTaylorPanel27_3.certificate, FiniteLowTaylorPanel27_4.certificate, FiniteLowTaylorPanel27_5.certificate, FiniteLowTaylorPanel27_12.certificate, FiniteLowTaylorPanel27_13.certificate,
  FiniteLowTaylorPanel28_3.certificate, FiniteLowTaylorPanel28_4.certificate, FiniteLowTaylorPanel28_5.certificate, FiniteLowTaylorPanel28_6.certificate, FiniteLowTaylorPanel28_13.certificate,
  FiniteLowTaylorPanel28_14.certificate, FiniteLowTaylorPanel29_4.certificate, FiniteLowTaylorPanel29_5.certificate, FiniteLowTaylorPanel29_6.certificate, FiniteLowTaylorPanel29_7.certificate,
  FiniteLowTaylorPanel29_14.certificate, FiniteLowTaylorPanel29_15.certificate, FiniteLowTaylorPanel30_3.certificate, FiniteLowTaylorPanel30_4.certificate, FiniteLowTaylorPanel30_6.certificate,
  FiniteLowTaylorPanel30_7.certificate, FiniteLowTaylorPanel30_14.certificate, FiniteLowTaylorPanel30_15.certificate, FiniteLowTaylorPanel31_2.certificate, FiniteLowTaylorPanel31_3.certificate,
  FiniteLowTaylorPanel31_5.certificate, FiniteLowTaylorPanel31_6.certificate, FiniteLowTaylorPanel31_10.certificate, FiniteLowTaylorPanel31_11.certificate, FiniteLowTaylorPanel32_2.certificate,
  FiniteLowTaylorPanel32_3.certificate, FiniteLowTaylorPanel32_6.certificate, FiniteLowTaylorPanel32_7.certificate, FiniteLowTaylorPanel32_12.certificate, FiniteLowTaylorPanel32_13.certificate,
  FiniteLowTaylorPanel33_2.certificate, FiniteLowTaylorPanel33_3.certificate, FiniteLowTaylorPanel33_6.certificate, FiniteLowTaylorPanel33_7.certificate, FiniteLowTaylorPanel33_14.certificate,
  FiniteLowTaylorPanel33_15.certificate, FiniteLowTaylorPanel34_1.certificate, FiniteLowTaylorPanel34_2.certificate, FiniteLowTaylorPanel34_3.certificate, FiniteLowTaylorPanel34_6.certificate,
  FiniteLowTaylorPanel34_7.certificate, FiniteLowTaylorPanel34_20.certificate, FiniteLowTaylorPanel34_21.certificate, FiniteLowTaylorPanel35_3.certificate, FiniteLowTaylorPanel35_4.certificate,
  FiniteLowTaylorPanel35_5.certificate, FiniteLowTaylorPanel35_6.certificate, FiniteLowTaylorPanel35_15.certificate, FiniteLowTaylorPanel35_16.certificate, FiniteLowTaylorPanel36_3.certificate,
  FiniteLowTaylorPanel36_4.certificate, FiniteLowTaylorPanel36_5.certificate, FiniteLowTaylorPanel36_6.certificate, FiniteLowTaylorPanel36_14.certificate, FiniteLowTaylorPanel36_15.certificate,
  FiniteLowTaylorPanel37_5.certificate, FiniteLowTaylorPanel37_6.certificate, FiniteLowTaylorPanel37_7.certificate, FiniteLowTaylorPanel37_8.certificate, FiniteLowTaylorPanel37_12.certificate,
  FiniteLowTaylorPanel37_13.certificate, FiniteLowTaylorPanel38_2.certificate, FiniteLowTaylorPanel38_3.certificate, FiniteLowTaylorPanel38_4.certificate, FiniteLowTaylorPanel38_8.certificate,
  FiniteLowTaylorPanel38_9.certificate, FiniteLowTaylorPanel38_21.certificate, FiniteLowTaylorPanel38_22.certificate, FiniteLowTaylorPanel39_2.certificate, FiniteLowTaylorPanel39_3.certificate,
  FiniteLowTaylorPanel39_4.certificate, FiniteLowTaylorPanel39_5.certificate, FiniteLowTaylorPanel39_12.certificate, FiniteLowTaylorPanel39_13.certificate, FiniteLowTaylorPanel40_2.certificate,
  FiniteLowTaylorPanel40_3.certificate, FiniteLowTaylorPanel40_4.certificate, FiniteLowTaylorPanel40_5.certificate, FiniteLowTaylorPanel40_12.certificate, FiniteLowTaylorPanel40_13.certificate,
  FiniteLowTaylorPanel41_2.certificate, FiniteLowTaylorPanel41_3.certificate, FiniteLowTaylorPanel41_4.certificate, FiniteLowTaylorPanel41_5.certificate, FiniteLowTaylorPanel41_13.certificate,
  FiniteLowTaylorPanel41_14.certificate, FiniteLowTaylorPanel42_3.certificate, FiniteLowTaylorPanel42_4.certificate, FiniteLowTaylorPanel42_5.certificate, FiniteLowTaylorPanel42_6.certificate,
  FiniteLowTaylorPanel42_15.certificate, FiniteLowTaylorPanel42_16.certificate, FiniteLowTaylorPanel43_3.certificate, FiniteLowTaylorPanel43_4.certificate, FiniteLowTaylorPanel43_5.certificate,
  FiniteLowTaylorPanel43_6.certificate, FiniteLowTaylorPanel43_16.certificate, FiniteLowTaylorPanel43_17.certificate, FiniteLowTaylorPanel44_4.certificate, FiniteLowTaylorPanel44_5.certificate,
  FiniteLowTaylorPanel44_6.certificate, FiniteLowTaylorPanel44_7.certificate, FiniteLowTaylorPanel44_17.certificate, FiniteLowTaylorPanel44_18.certificate, FiniteLowTaylorPanel45_4.certificate,
  FiniteLowTaylorPanel45_5.certificate, FiniteLowTaylorPanel45_6.certificate, FiniteLowTaylorPanel45_7.certificate, FiniteLowTaylorPanel45_15.certificate, FiniteLowTaylorPanel45_16.certificate,
  FiniteLowTaylorPanel46_4.certificate, FiniteLowTaylorPanel46_5.certificate, FiniteLowTaylorPanel46_6.certificate, FiniteLowTaylorPanel46_7.certificate, FiniteLowTaylorPanel46_14.certificate,
  FiniteLowTaylorPanel46_15.certificate, FiniteLowTaylorPanel47_2.certificate, FiniteLowTaylorPanel47_3.certificate, FiniteLowTaylorPanel47_6.certificate, FiniteLowTaylorPanel47_7.certificate,
  FiniteLowTaylorPanel47_14.certificate, FiniteLowTaylorPanel47_15.certificate, FiniteLowTaylorPanel48_1.certificate, FiniteLowTaylorPanel48_4.certificate, FiniteLowTaylorPanel48_5.certificate,
  FiniteLowTaylorPanel48_18.certificate, FiniteLowTaylorPanel48_19.certificate, FiniteLowTaylorPanel48_22.certificate, FiniteLowTaylorPanel48_23.certificate, FiniteLowTaylorPanel48_24.certificate,
  FiniteLowTaylorPanel48_25.certificate, FiniteLowTaylorPanel49_2.certificate, FiniteLowTaylorPanel49_3.certificate, FiniteLowTaylorPanel49_6.certificate, FiniteLowTaylorPanel49_7.certificate,
  FiniteLowTaylorPanel49_12.certificate, FiniteLowTaylorPanel49_13.certificate, FiniteLowTaylorPanel50_3.certificate, FiniteLowTaylorPanel50_4.certificate, FiniteLowTaylorPanel50_5.certificate,
  FiniteLowTaylorPanel50_6.certificate, FiniteLowTaylorPanel50_15.certificate, FiniteLowTaylorPanel50_16.certificate, FiniteLowTaylorPanel51_5.certificate, FiniteLowTaylorPanel51_6.certificate,
  FiniteLowTaylorPanel51_7.certificate, FiniteLowTaylorPanel51_8.certificate, FiniteLowTaylorPanel51_13.certificate, FiniteLowTaylorPanel51_14.certificate, FiniteLowTaylorPanel52_2.certificate,
  FiniteLowTaylorPanel52_3.certificate, FiniteLowTaylorPanel52_4.certificate, FiniteLowTaylorPanel52_7.certificate, FiniteLowTaylorPanel52_8.certificate, FiniteLowTaylorPanel52_22.certificate,
  FiniteLowTaylorPanel52_23.certificate, FiniteLowTaylorPanel53_2.certificate, FiniteLowTaylorPanel53_3.certificate, FiniteLowTaylorPanel53_4.certificate, FiniteLowTaylorPanel53_5.certificate,
  FiniteLowTaylorPanel53_12.certificate, FiniteLowTaylorPanel53_13.certificate, FiniteLowTaylorPanel54_2.certificate, FiniteLowTaylorPanel54_3.certificate, FiniteLowTaylorPanel54_4.certificate,
  FiniteLowTaylorPanel54_5.certificate, FiniteLowTaylorPanel54_12.certificate, FiniteLowTaylorPanel54_13.certificate, FiniteLowTaylorPanel55_2.certificate, FiniteLowTaylorPanel55_3.certificate,
  FiniteLowTaylorPanel55_4.certificate, FiniteLowTaylorPanel55_5.certificate, FiniteLowTaylorPanel55_13.certificate, FiniteLowTaylorPanel55_14.certificate, FiniteLowTaylorPanel56_2.certificate,
  FiniteLowTaylorPanel56_3.certificate, FiniteLowTaylorPanel56_4.certificate, FiniteLowTaylorPanel56_5.certificate, FiniteLowTaylorPanel56_14.certificate, FiniteLowTaylorPanel56_15.certificate,
  FiniteLowTaylorPanel57_2.certificate, FiniteLowTaylorPanel57_3.certificate, FiniteLowTaylorPanel57_4.certificate, FiniteLowTaylorPanel57_5.certificate, FiniteLowTaylorPanel57_16.certificate,
  FiniteLowTaylorPanel57_17.certificate, FiniteLowTaylorPanel58_3.certificate, FiniteLowTaylorPanel58_4.certificate, FiniteLowTaylorPanel58_5.certificate, FiniteLowTaylorPanel58_6.certificate,
  FiniteLowTaylorPanel58_17.certificate, FiniteLowTaylorPanel58_18.certificate, FiniteLowTaylorPanel59_4.certificate, FiniteLowTaylorPanel59_5.certificate, FiniteLowTaylorPanel59_6.certificate,
  FiniteLowTaylorPanel59_7.certificate, FiniteLowTaylorPanel59_17.certificate, FiniteLowTaylorPanel59_18.certificate, FiniteLowTaylorPanel60_1.certificate, FiniteLowTaylorPanel60_2.certificate,
  FiniteLowTaylorPanel60_3.certificate, FiniteLowTaylorPanel60_6.certificate, FiniteLowTaylorPanel60_7.certificate, FiniteLowTaylorPanel60_18.certificate, FiniteLowTaylorPanel60_19.certificate,
  FiniteLowTaylorPanel61_1.certificate, FiniteLowTaylorPanel61_2.certificate, FiniteLowTaylorPanel61_3.certificate, FiniteLowTaylorPanel61_13.certificate, FiniteLowTaylorPanel61_14.certificate,
  FiniteLowTaylorPanel61_23.certificate, FiniteLowTaylorPanel61_24.certificate, FiniteLowTaylorPanel62_2.certificate, FiniteLowTaylorPanel62_3.certificate, FiniteLowTaylorPanel62_6.certificate,
  FiniteLowTaylorPanel62_7.certificate, FiniteLowTaylorPanel62_14.certificate, FiniteLowTaylorPanel62_15.certificate, FiniteLowTaylorPanel63_3.certificate, FiniteLowTaylorPanel63_4.certificate,
  FiniteLowTaylorPanel63_7.certificate, FiniteLowTaylorPanel63_8.certificate, FiniteLowTaylorPanel63_13.certificate, FiniteLowTaylorPanel63_14.certificate, FiniteLowTaylorPanel64_4.certificate,
  FiniteLowTaylorPanel64_5.certificate, FiniteLowTaylorPanel64_6.certificate, FiniteLowTaylorPanel64_7.certificate, FiniteLowTaylorPanel64_14.certificate, FiniteLowTaylorPanel64_15.certificate,
  FiniteLowTaylorPanel65_2.certificate, FiniteLowTaylorPanel65_3.certificate, FiniteLowTaylorPanel65_4.certificate, FiniteLowTaylorPanel65_9.certificate, FiniteLowTaylorPanel65_10.certificate,
  FiniteLowTaylorPanel65_21.certificate, FiniteLowTaylorPanel65_22.certificate, FiniteLowTaylorPanel66_2.certificate, FiniteLowTaylorPanel66_3.certificate, FiniteLowTaylorPanel66_4.certificate,
  FiniteLowTaylorPanel66_5.certificate, FiniteLowTaylorPanel66_12.certificate, FiniteLowTaylorPanel66_13.certificate, FiniteLowTaylorPanel67_2.certificate, FiniteLowTaylorPanel67_3.certificate,
  FiniteLowTaylorPanel67_4.certificate, FiniteLowTaylorPanel67_5.certificate, FiniteLowTaylorPanel67_12.certificate, FiniteLowTaylorPanel67_13.certificate, FiniteLowTaylorPanel68_1.certificate,
  FiniteLowTaylorPanel68_2.certificate, FiniteLowTaylorPanel68_3.certificate, FiniteLowTaylorPanel68_15.certificate, FiniteLowTaylorPanel68_16.certificate, FiniteLowTaylorPanel68_27.certificate,
  FiniteLowTaylorPanel68_28.certificate, FiniteLowTaylorPanel68_29.certificate, FiniteLowTaylorPanel68_30.certificate, FiniteLowTaylorPanel69_1.certificate, FiniteLowTaylorPanel69_2.certificate,
  FiniteLowTaylorPanel69_3.certificate, FiniteLowTaylorPanel69_10.certificate, FiniteLowTaylorPanel69_11.certificate, FiniteLowTaylorPanel69_24.certificate, FiniteLowTaylorPanel69_25.certificate,
  FiniteLowTaylorPanel70_3.certificate, FiniteLowTaylorPanel70_4.certificate, FiniteLowTaylorPanel70_5.certificate, FiniteLowTaylorPanel70_6.certificate, FiniteLowTaylorPanel70_15.certificate,
  FiniteLowTaylorPanel70_16.certificate, FiniteLowTaylorPanel71_1.certificate, FiniteLowTaylorPanel71_2.certificate, FiniteLowTaylorPanel71_3.certificate, FiniteLowTaylorPanel71_11.certificate,
  FiniteLowTaylorPanel71_12.certificate, FiniteLowTaylorPanel71_22.certificate, FiniteLowTaylorPanel71_23.certificate, FiniteLowTaylorPanel72_2.certificate, FiniteLowTaylorPanel72_3.certificate,
  FiniteLowTaylorPanel72_4.certificate, FiniteLowTaylorPanel72_5.certificate, FiniteLowTaylorPanel72_13.certificate, FiniteLowTaylorPanel72_14.certificate, FiniteLowTaylorPanel73_3.certificate,
  FiniteLowTaylorPanel73_4.certificate, FiniteLowTaylorPanel73_5.certificate, FiniteLowTaylorPanel73_6.certificate, FiniteLowTaylorPanel73_14.certificate, FiniteLowTaylorPanel73_15.certificate,
  FiniteLowTaylorPanel74_3.certificate, FiniteLowTaylorPanel74_4.certificate, FiniteLowTaylorPanel74_7.certificate, FiniteLowTaylorPanel74_8.certificate, FiniteLowTaylorPanel74_15.certificate,
  FiniteLowTaylorPanel74_16.certificate, FiniteLowTaylorPanel75_3.certificate, FiniteLowTaylorPanel75_4.certificate, FiniteLowTaylorPanel75_5.certificate, FiniteLowTaylorPanel75_6.certificate,
  FiniteLowTaylorPanel75_13.certificate, FiniteLowTaylorPanel75_14.certificate, FiniteLowTaylorPanel76_2.certificate, FiniteLowTaylorPanel76_4.certificate, FiniteLowTaylorPanel76_5.certificate,
  FiniteLowTaylorPanel76_12.certificate, FiniteLowTaylorPanel76_13.certificate, FiniteLowTaylorPanel76_23.certificate, FiniteLowTaylorPanel76_24.certificate, FiniteLowTaylorPanel76_27.certificate,
  FiniteLowTaylorPanel76_28.certificate, FiniteLowTaylorPanel77_2.certificate, FiniteLowTaylorPanel77_7.certificate, FiniteLowTaylorPanel77_8.certificate, FiniteLowTaylorPanel77_18.certificate,
  FiniteLowTaylorPanel77_19.certificate, FiniteLowTaylorPanel77_31.certificate, FiniteLowTaylorPanel77_32.certificate, FiniteLowTaylorPanel77_33.certificate, FiniteLowTaylorPanel77_34.certificate,
  FiniteLowTaylorPanel78_2.certificate, FiniteLowTaylorPanel78_3.certificate, FiniteLowTaylorPanel78_4.certificate, FiniteLowTaylorPanel78_11.certificate, FiniteLowTaylorPanel78_12.certificate,
  FiniteLowTaylorPanel78_21.certificate, FiniteLowTaylorPanel78_22.certificate, FiniteLowTaylorPanel79_2.certificate, FiniteLowTaylorPanel79_3.certificate, FiniteLowTaylorPanel79_4.certificate,
  FiniteLowTaylorPanel79_5.certificate, FiniteLowTaylorPanel79_10.certificate, FiniteLowTaylorPanel79_11.certificate, FiniteLowTaylorPanel80_1.certificate, FiniteLowTaylorPanel80_2.certificate,
  FiniteLowTaylorPanel80_3.certificate, FiniteLowTaylorPanel80_4.certificate, FiniteLowTaylorPanel80_11.certificate, FiniteLowTaylorPanel80_12.certificate, FiniteLowTaylorPanel81_2.certificate,
  FiniteLowTaylorPanel81_3.certificate, FiniteLowTaylorPanel81_4.certificate, FiniteLowTaylorPanel81_5.certificate, FiniteLowTaylorPanel81_15.certificate, FiniteLowTaylorPanel81_16.certificate,
  FiniteLowTaylorPanel82_4.certificate, FiniteLowTaylorPanel82_5.certificate, FiniteLowTaylorPanel82_6.certificate, FiniteLowTaylorPanel82_7.certificate, FiniteLowTaylorPanel82_15.certificate,
  FiniteLowTaylorPanel82_16.certificate, FiniteLowTaylorPanel83_4.certificate, FiniteLowTaylorPanel83_5.certificate, FiniteLowTaylorPanel83_7.certificate, FiniteLowTaylorPanel83_8.certificate,
  FiniteLowTaylorPanel83_17.certificate, FiniteLowTaylorPanel83_18.certificate, FiniteLowTaylorPanel84_2.certificate, FiniteLowTaylorPanel84_4.certificate, FiniteLowTaylorPanel84_5.certificate,
  FiniteLowTaylorPanel84_9.certificate, FiniteLowTaylorPanel84_10.certificate, FiniteLowTaylorPanel85_2.certificate, FiniteLowTaylorPanel85_6.certificate, FiniteLowTaylorPanel85_7.certificate,
  FiniteLowTaylorPanel85_13.certificate, FiniteLowTaylorPanel85_14.certificate, FiniteLowTaylorPanel85_27.certificate, FiniteLowTaylorPanel85_28.certificate, FiniteLowTaylorPanel85_29.certificate,
  FiniteLowTaylorPanel85_30.certificate, FiniteLowTaylorPanel86_2.certificate, FiniteLowTaylorPanel86_4.certificate, FiniteLowTaylorPanel86_5.certificate, FiniteLowTaylorPanel86_11.certificate,
  FiniteLowTaylorPanel86_12.certificate, FiniteLowTaylorPanel86_19.certificate, FiniteLowTaylorPanel86_20.certificate, FiniteLowTaylorPanel87_2.certificate, FiniteLowTaylorPanel87_5.certificate,
  FiniteLowTaylorPanel87_6.certificate, FiniteLowTaylorPanel87_12.certificate, FiniteLowTaylorPanel87_13.certificate, FiniteLowTaylorPanel87_23.certificate, FiniteLowTaylorPanel87_24.certificate,
  FiniteLowTaylorPanel88_2.certificate, FiniteLowTaylorPanel88_3.certificate, FiniteLowTaylorPanel88_4.certificate, FiniteLowTaylorPanel88_5.certificate, FiniteLowTaylorPanel88_13.certificate,
  FiniteLowTaylorPanel88_14.certificate, FiniteLowTaylorPanel89_2.certificate, FiniteLowTaylorPanel89_3.certificate, FiniteLowTaylorPanel89_4.certificate, FiniteLowTaylorPanel89_5.certificate,
  FiniteLowTaylorPanel89_11.certificate, FiniteLowTaylorPanel89_12.certificate, FiniteLowTaylorPanel90_1.certificate, FiniteLowTaylorPanel90_2.certificate, FiniteLowTaylorPanel90_3.certificate,
  FiniteLowTaylorPanel90_4.certificate, FiniteLowTaylorPanel90_15.certificate, FiniteLowTaylorPanel90_16.certificate, FiniteLowTaylorPanel91_4.certificate, FiniteLowTaylorPanel91_5.certificate,
  FiniteLowTaylorPanel91_6.certificate, FiniteLowTaylorPanel91_7.certificate, FiniteLowTaylorPanel91_19.certificate, FiniteLowTaylorPanel91_20.certificate, FiniteLowTaylorPanel92_4.certificate,
  FiniteLowTaylorPanel92_5.certificate, FiniteLowTaylorPanel92_7.certificate, FiniteLowTaylorPanel92_8.certificate, FiniteLowTaylorPanel92_17.certificate, FiniteLowTaylorPanel92_18.certificate,
  FiniteLowTaylorPanel93_2.certificate, FiniteLowTaylorPanel93_4.certificate, FiniteLowTaylorPanel93_5.certificate, FiniteLowTaylorPanel93_9.certificate, FiniteLowTaylorPanel93_10.certificate,
  FiniteLowTaylorPanel94_2.certificate, FiniteLowTaylorPanel94_3.certificate, FiniteLowTaylorPanel94_4.certificate, FiniteLowTaylorPanel94_8.certificate, FiniteLowTaylorPanel94_9.certificate,
  FiniteLowTaylorPanel94_15.certificate, FiniteLowTaylorPanel94_16.certificate, FiniteLowTaylorPanel95_2.certificate, FiniteLowTaylorPanel95_4.certificate, FiniteLowTaylorPanel95_5.certificate,
  FiniteLowTaylorPanel95_12.certificate, FiniteLowTaylorPanel95_13.certificate, FiniteLowTaylorPanel95_18.certificate, FiniteLowTaylorPanel95_19.certificate, FiniteLowTaylorPanel96_2.certificate,
  FiniteLowTaylorPanel96_5.certificate, FiniteLowTaylorPanel96_6.certificate, FiniteLowTaylorPanel96_15.certificate, FiniteLowTaylorPanel96_16.certificate, FiniteLowTaylorPanel96_23.certificate,
  FiniteLowTaylorPanel96_24.certificate, FiniteLowTaylorPanel97_2.certificate, FiniteLowTaylorPanel97_3.certificate, FiniteLowTaylorPanel97_6.certificate, FiniteLowTaylorPanel97_7.certificate,
  FiniteLowTaylorPanel97_16.certificate, FiniteLowTaylorPanel97_17.certificate, FiniteLowTaylorPanel98_2.certificate, FiniteLowTaylorPanel98_3.certificate, FiniteLowTaylorPanel98_6.certificate,
  FiniteLowTaylorPanel98_7.certificate, FiniteLowTaylorPanel98_16.certificate, FiniteLowTaylorPanel98_17.certificate, FiniteLowTaylorPanel99_1.certificate, FiniteLowTaylorPanel99_2.certificate,
  FiniteLowTaylorPanel99_3.certificate, FiniteLowTaylorPanel99_4.certificate, FiniteLowTaylorPanel99_17.certificate, FiniteLowTaylorPanel99_18.certificate, FiniteLowTaylorPanel100_3.certificate,
  FiniteLowTaylorPanel100_4.certificate, FiniteLowTaylorPanel100_6.certificate, FiniteLowTaylorPanel100_7.certificate, FiniteLowTaylorPanel100_17.certificate, FiniteLowTaylorPanel100_18.certificate,
  FiniteLowTaylorPanel101_4.certificate, FiniteLowTaylorPanel101_5.certificate, FiniteLowTaylorPanel101_7.certificate, FiniteLowTaylorPanel101_8.certificate, FiniteLowTaylorPanel101_19.certificate,
  FiniteLowTaylorPanel101_20.certificate, FiniteLowTaylorPanel102_2.certificate, FiniteLowTaylorPanel102_4.certificate, FiniteLowTaylorPanel102_5.certificate, FiniteLowTaylorPanel102_7.certificate,
  FiniteLowTaylorPanel102_8.certificate, FiniteLowTaylorPanel103_2.certificate, FiniteLowTaylorPanel103_3.certificate, FiniteLowTaylorPanel103_4.certificate, FiniteLowTaylorPanel103_11.certificate,
  FiniteLowTaylorPanel103_12.certificate, FiniteLowTaylorPanel103_15.certificate, FiniteLowTaylorPanel103_16.certificate, FiniteLowTaylorPanel104_3.certificate, FiniteLowTaylorPanel104_4.certificate,
  FiniteLowTaylorPanel104_5.certificate, FiniteLowTaylorPanel104_13.certificate, FiniteLowTaylorPanel104_14.certificate, FiniteLowTaylorPanel104_19.certificate, FiniteLowTaylorPanel104_20.certificate,
  FiniteLowTaylorPanel105_2.certificate, FiniteLowTaylorPanel105_5.certificate, FiniteLowTaylorPanel105_6.certificate, FiniteLowTaylorPanel105_15.certificate, FiniteLowTaylorPanel105_16.certificate,
  FiniteLowTaylorPanel105_23.certificate, FiniteLowTaylorPanel105_24.certificate, FiniteLowTaylorPanel106_2.certificate, FiniteLowTaylorPanel106_3.certificate, FiniteLowTaylorPanel106_6.certificate,
  FiniteLowTaylorPanel106_7.certificate, FiniteLowTaylorPanel106_17.certificate, FiniteLowTaylorPanel106_18.certificate, FiniteLowTaylorPanel107_2.certificate, FiniteLowTaylorPanel107_3.certificate,
  FiniteLowTaylorPanel107_7.certificate, FiniteLowTaylorPanel107_8.certificate, FiniteLowTaylorPanel107_19.certificate, FiniteLowTaylorPanel107_20.certificate, FiniteLowTaylorPanel108_1.certificate,
  FiniteLowTaylorPanel108_2.certificate, FiniteLowTaylorPanel108_3.certificate, FiniteLowTaylorPanel108_4.certificate, FiniteLowTaylorPanel108_17.certificate, FiniteLowTaylorPanel108_18.certificate,
  FiniteLowTaylorPanel109_3.certificate, FiniteLowTaylorPanel109_4.certificate, FiniteLowTaylorPanel109_6.certificate, FiniteLowTaylorPanel109_7.certificate, FiniteLowTaylorPanel109_19.certificate,
  FiniteLowTaylorPanel109_20.certificate, FiniteLowTaylorPanel110_2.certificate, FiniteLowTaylorPanel110_4.certificate, FiniteLowTaylorPanel110_5.certificate, FiniteLowTaylorPanel110_7.certificate,
  FiniteLowTaylorPanel110_8.certificate, FiniteLowTaylorPanel111_2.certificate, FiniteLowTaylorPanel111_4.certificate, FiniteLowTaylorPanel111_5.certificate, FiniteLowTaylorPanel111_11.certificate,
  FiniteLowTaylorPanel111_12.certificate, FiniteLowTaylorPanel112_2.certificate, FiniteLowTaylorPanel112_3.certificate, FiniteLowTaylorPanel112_4.certificate, FiniteLowTaylorPanel112_11.certificate,
  FiniteLowTaylorPanel112_12.certificate, FiniteLowTaylorPanel112_16.certificate, FiniteLowTaylorPanel112_17.certificate, FiniteLowTaylorPanel113_3.certificate, FiniteLowTaylorPanel113_4.certificate,
  FiniteLowTaylorPanel113_5.certificate, FiniteLowTaylorPanel113_13.certificate, FiniteLowTaylorPanel113_14.certificate, FiniteLowTaylorPanel113_20.certificate, FiniteLowTaylorPanel113_21.certificate,
  FiniteLowTaylorPanel114_2.certificate, FiniteLowTaylorPanel114_5.certificate, FiniteLowTaylorPanel114_6.certificate, FiniteLowTaylorPanel114_15.certificate, FiniteLowTaylorPanel114_16.certificate,
  FiniteLowTaylorPanel114_22.certificate, FiniteLowTaylorPanel114_23.certificate, FiniteLowTaylorPanel115_2.certificate, FiniteLowTaylorPanel115_3.certificate, FiniteLowTaylorPanel115_6.certificate,
  FiniteLowTaylorPanel115_7.certificate, FiniteLowTaylorPanel115_18.certificate, FiniteLowTaylorPanel115_19.certificate, FiniteLowTaylorPanel116_2.certificate, FiniteLowTaylorPanel116_3.certificate,
  FiniteLowTaylorPanel116_7.certificate, FiniteLowTaylorPanel116_8.certificate, FiniteLowTaylorPanel116_20.certificate, FiniteLowTaylorPanel116_21.certificate, FiniteLowTaylorPanel117_3.certificate,
  FiniteLowTaylorPanel117_4.certificate, FiniteLowTaylorPanel117_8.certificate, FiniteLowTaylorPanel117_9.certificate, FiniteLowTaylorPanel117_19.certificate, FiniteLowTaylorPanel117_20.certificate,
  FiniteLowTaylorPanel118_2.certificate, FiniteLowTaylorPanel118_3.certificate, FiniteLowTaylorPanel118_7.certificate, FiniteLowTaylorPanel118_8.certificate, FiniteLowTaylorPanel118_19.certificate,
  FiniteLowTaylorPanel118_20.certificate, FiniteLowTaylorPanel119_2.certificate, FiniteLowTaylorPanel119_4.certificate, FiniteLowTaylorPanel119_5.certificate, FiniteLowTaylorPanel119_10.certificate,
  FiniteLowTaylorPanel119_11.certificate, FiniteLowTaylorPanel120_2.certificate, FiniteLowTaylorPanel120_6.certificate, FiniteLowTaylorPanel120_7.certificate, FiniteLowTaylorPanel120_12.certificate,
  FiniteLowTaylorPanel120_13.certificate, FiniteLowTaylorPanel121_2.certificate, FiniteLowTaylorPanel121_3.certificate, FiniteLowTaylorPanel121_4.certificate, FiniteLowTaylorPanel121_11.certificate,
  FiniteLowTaylorPanel121_12.certificate, FiniteLowTaylorPanel121_16.certificate, FiniteLowTaylorPanel121_17.certificate, FiniteLowTaylorPanel122_2.certificate, FiniteLowTaylorPanel122_3.certificate,
  FiniteLowTaylorPanel122_4.certificate, FiniteLowTaylorPanel122_12.certificate, FiniteLowTaylorPanel122_13.certificate, FiniteLowTaylorPanel122_18.certificate, FiniteLowTaylorPanel122_19.certificate,
  FiniteLowTaylorPanel123_4.certificate, FiniteLowTaylorPanel123_5.certificate, FiniteLowTaylorPanel123_6.certificate, FiniteLowTaylorPanel123_15.certificate, FiniteLowTaylorPanel123_16.certificate,
  FiniteLowTaylorPanel123_22.certificate, FiniteLowTaylorPanel123_23.certificate, FiniteLowTaylorPanel124_2.certificate, FiniteLowTaylorPanel124_3.certificate, FiniteLowTaylorPanel124_6.certificate,
  FiniteLowTaylorPanel124_7.certificate, FiniteLowTaylorPanel124_16.certificate, FiniteLowTaylorPanel124_17.certificate, FiniteLowTaylorPanel125_3.certificate, FiniteLowTaylorPanel125_4.certificate,
  FiniteLowTaylorPanel125_8.certificate, FiniteLowTaylorPanel125_9.certificate, FiniteLowTaylorPanel125_19.certificate, FiniteLowTaylorPanel125_20.certificate, FiniteLowTaylorPanel126_3.certificate,
  FiniteLowTaylorPanel126_4.certificate, FiniteLowTaylorPanel126_8.certificate, FiniteLowTaylorPanel126_9.certificate, FiniteLowTaylorPanel126_19.certificate, FiniteLowTaylorPanel126_20.certificate,
  FiniteLowTaylorPanel127_2.certificate, FiniteLowTaylorPanel127_3.certificate, FiniteLowTaylorPanel127_9.certificate, FiniteLowTaylorPanel127_10.certificate, FiniteLowTaylorPanel127_19.certificate,
  FiniteLowTaylorPanel127_20.certificate, FiniteLowTaylorPanel128_2.certificate, FiniteLowTaylorPanel128_3.certificate, FiniteLowTaylorPanel128_4.certificate, FiniteLowTaylorPanel128_9.certificate,
  FiniteLowTaylorPanel128_10.certificate, FiniteLowTaylorPanel129_2.certificate, FiniteLowTaylorPanel129_4.certificate, FiniteLowTaylorPanel129_5.certificate, FiniteLowTaylorPanel129_14.certificate,
  FiniteLowTaylorPanel129_15.certificate, FiniteLowTaylorPanel130_2.certificate, FiniteLowTaylorPanel130_5.certificate, FiniteLowTaylorPanel130_6.certificate, FiniteLowTaylorPanel130_11.certificate,
  FiniteLowTaylorPanel130_12.certificate, FiniteLowTaylorPanel130_15.certificate, FiniteLowTaylorPanel130_16.certificate, FiniteLowTaylorPanel131_3.certificate, FiniteLowTaylorPanel131_6.certificate,
  FiniteLowTaylorPanel131_7.certificate, FiniteLowTaylorPanel131_13.certificate, FiniteLowTaylorPanel131_14.certificate, FiniteLowTaylorPanel131_19.certificate, FiniteLowTaylorPanel131_20.certificate,
  FiniteLowTaylorPanel132_4.certificate, FiniteLowTaylorPanel132_7.certificate, FiniteLowTaylorPanel132_8.certificate, FiniteLowTaylorPanel132_15.certificate, FiniteLowTaylorPanel132_16.certificate,
  FiniteLowTaylorPanel132_21.certificate, FiniteLowTaylorPanel132_22.certificate, FiniteLowTaylorPanel133_2.certificate, FiniteLowTaylorPanel133_3.certificate, FiniteLowTaylorPanel133_8.certificate,
  FiniteLowTaylorPanel133_9.certificate, FiniteLowTaylorPanel133_16.certificate, FiniteLowTaylorPanel133_17.certificate, FiniteLowTaylorPanel134_3.certificate, FiniteLowTaylorPanel134_4.certificate,
  FiniteLowTaylorPanel134_8.certificate, FiniteLowTaylorPanel134_9.certificate, FiniteLowTaylorPanel134_19.certificate, FiniteLowTaylorPanel134_20.certificate, FiniteLowTaylorPanel135_3.certificate,
  FiniteLowTaylorPanel135_4.certificate, FiniteLowTaylorPanel135_8.certificate, FiniteLowTaylorPanel135_9.certificate, FiniteLowTaylorPanel135_19.certificate, FiniteLowTaylorPanel135_20.certificate,
  FiniteLowTaylorPanel136_2.certificate, FiniteLowTaylorPanel136_3.certificate, FiniteLowTaylorPanel136_4.certificate, FiniteLowTaylorPanel136_9.certificate, FiniteLowTaylorPanel136_10.certificate,
  FiniteLowTaylorPanel137_2.certificate, FiniteLowTaylorPanel137_3.certificate, FiniteLowTaylorPanel137_4.certificate, FiniteLowTaylorPanel137_9.certificate, FiniteLowTaylorPanel137_10.certificate,
  FiniteLowTaylorPanel138_2.certificate, FiniteLowTaylorPanel138_4.certificate, FiniteLowTaylorPanel138_5.certificate, FiniteLowTaylorPanel138_14.certificate, FiniteLowTaylorPanel138_15.certificate,
  FiniteLowTaylorPanel139_2.certificate, FiniteLowTaylorPanel139_5.certificate, FiniteLowTaylorPanel139_6.certificate, FiniteLowTaylorPanel139_11.certificate, FiniteLowTaylorPanel139_12.certificate,
  FiniteLowTaylorPanel139_13.certificate, FiniteLowTaylorPanel139_14.certificate, FiniteLowTaylorPanel140_2.certificate, FiniteLowTaylorPanel140_5.certificate, FiniteLowTaylorPanel140_6.certificate,
  FiniteLowTaylorPanel140_11.certificate, FiniteLowTaylorPanel140_12.certificate, FiniteLowTaylorPanel140_15.certificate, FiniteLowTaylorPanel140_16.certificate, FiniteLowTaylorPanel141_2.certificate,
  FiniteLowTaylorPanel141_5.certificate, FiniteLowTaylorPanel141_6.certificate, FiniteLowTaylorPanel141_11.certificate, FiniteLowTaylorPanel141_12.certificate, FiniteLowTaylorPanel141_17.certificate,
  FiniteLowTaylorPanel141_18.certificate, FiniteLowTaylorPanel142_2.certificate, FiniteLowTaylorPanel142_5.certificate, FiniteLowTaylorPanel142_6.certificate, FiniteLowTaylorPanel142_12.certificate,
  FiniteLowTaylorPanel142_13.certificate, FiniteLowTaylorPanel142_19.certificate, FiniteLowTaylorPanel142_20.certificate, FiniteLowTaylorPanel143_3.certificate, FiniteLowTaylorPanel143_6.certificate,
  FiniteLowTaylorPanel143_7.certificate, FiniteLowTaylorPanel143_13.certificate, FiniteLowTaylorPanel143_14.certificate, FiniteLowTaylorPanel143_19.certificate, FiniteLowTaylorPanel143_20.certificate,
  FiniteLowTaylorPanel144_4.certificate, FiniteLowTaylorPanel144_7.certificate, FiniteLowTaylorPanel144_8.certificate, FiniteLowTaylorPanel144_15.certificate, FiniteLowTaylorPanel144_16.certificate,
  FiniteLowTaylorPanel144_21.certificate, FiniteLowTaylorPanel144_22.certificate, FiniteLowTaylorPanel145_4.certificate, FiniteLowTaylorPanel145_5.certificate, FiniteLowTaylorPanel145_8.certificate,
  FiniteLowTaylorPanel145_9.certificate, FiniteLowTaylorPanel145_16.certificate, FiniteLowTaylorPanel145_17.certificate, FiniteLowTaylorPanel146_5.certificate, FiniteLowTaylorPanel146_6.certificate,
  FiniteLowTaylorPanel146_10.certificate, FiniteLowTaylorPanel146_11.certificate, FiniteLowTaylorPanel146_17.certificate, FiniteLowTaylorPanel146_18.certificate, FiniteLowTaylorPanel147_3.certificate,
  FiniteLowTaylorPanel147_4.certificate, FiniteLowTaylorPanel147_10.certificate, FiniteLowTaylorPanel147_11.certificate, FiniteLowTaylorPanel147_19.certificate, FiniteLowTaylorPanel147_20.certificate,
  FiniteLowTaylorPanel148_3.certificate, FiniteLowTaylorPanel148_4.certificate, FiniteLowTaylorPanel148_11.certificate, FiniteLowTaylorPanel148_12.certificate, FiniteLowTaylorPanel148_17.certificate,
  FiniteLowTaylorPanel148_18.certificate, FiniteLowTaylorPanel148_28.certificate, FiniteLowTaylorPanel148_29.certificate, FiniteLowTaylorPanel149_3.certificate, FiniteLowTaylorPanel149_4.certificate,
  FiniteLowTaylorPanel149_5.certificate, FiniteLowTaylorPanel149_12.certificate, FiniteLowTaylorPanel149_13.certificate, FiniteLowTaylorPanel150_2.certificate, FiniteLowTaylorPanel150_3.certificate,
  FiniteLowTaylorPanel150_6.certificate, FiniteLowTaylorPanel150_7.certificate, FiniteLowTaylorPanel150_17.certificate, FiniteLowTaylorPanel150_18.certificate, FiniteLowTaylorPanel151_2.certificate,
  FiniteLowTaylorPanel151_3.certificate, FiniteLowTaylorPanel151_7.certificate, FiniteLowTaylorPanel151_8.certificate, FiniteLowTaylorPanel151_18.certificate, FiniteLowTaylorPanel151_19.certificate,
  FiniteLowTaylorPanel152_2.certificate, FiniteLowTaylorPanel152_3.certificate, FiniteLowTaylorPanel152_10.certificate, FiniteLowTaylorPanel152_11.certificate, FiniteLowTaylorPanel152_17.certificate,
  FiniteLowTaylorPanel152_18.certificate, FiniteLowTaylorPanel153_3.certificate, FiniteLowTaylorPanel153_5.certificate, FiniteLowTaylorPanel153_6.certificate, FiniteLowTaylorPanel153_11.certificate,
  FiniteLowTaylorPanel153_12.certificate, FiniteLowTaylorPanel153_13.certificate, FiniteLowTaylorPanel153_14.certificate, FiniteLowTaylorPanel154_3.certificate, FiniteLowTaylorPanel154_5.certificate,
  FiniteLowTaylorPanel154_6.certificate, FiniteLowTaylorPanel154_11.certificate, FiniteLowTaylorPanel154_12.certificate, FiniteLowTaylorPanel154_14.certificate, FiniteLowTaylorPanel154_15.certificate,
  FiniteLowTaylorPanel155_3.certificate, FiniteLowTaylorPanel155_6.certificate, FiniteLowTaylorPanel155_7.certificate, FiniteLowTaylorPanel155_12.certificate, FiniteLowTaylorPanel155_13.certificate,
  FiniteLowTaylorPanel155_16.certificate, FiniteLowTaylorPanel155_17.certificate, FiniteLowTaylorPanel156_3.certificate, FiniteLowTaylorPanel156_6.certificate, FiniteLowTaylorPanel156_7.certificate,
  FiniteLowTaylorPanel156_12.certificate, FiniteLowTaylorPanel156_13.certificate, FiniteLowTaylorPanel156_18.certificate, FiniteLowTaylorPanel156_19.certificate, FiniteLowTaylorPanel157_4.certificate,
  FiniteLowTaylorPanel157_7.certificate, FiniteLowTaylorPanel157_8.certificate, FiniteLowTaylorPanel157_14.certificate, FiniteLowTaylorPanel157_15.certificate, FiniteLowTaylorPanel157_19.certificate,
  FiniteLowTaylorPanel157_20.certificate, FiniteLowTaylorPanel158_5.certificate, FiniteLowTaylorPanel158_8.certificate, FiniteLowTaylorPanel158_9.certificate, FiniteLowTaylorPanel158_16.certificate,
  FiniteLowTaylorPanel158_17.certificate, FiniteLowTaylorPanel158_20.certificate, FiniteLowTaylorPanel158_21.certificate, FiniteLowTaylorPanel159_5.certificate, FiniteLowTaylorPanel159_6.certificate,
  FiniteLowTaylorPanel159_9.certificate, FiniteLowTaylorPanel159_10.certificate, FiniteLowTaylorPanel159_17.certificate, FiniteLowTaylorPanel159_18.certificate, FiniteLowTaylorPanel160_5.certificate,
  FiniteLowTaylorPanel160_6.certificate, FiniteLowTaylorPanel160_9.certificate, FiniteLowTaylorPanel160_10.certificate, FiniteLowTaylorPanel160_14.certificate, FiniteLowTaylorPanel160_15.certificate,
  FiniteLowTaylorPanel160_28.certificate, FiniteLowTaylorPanel160_29.certificate, FiniteLowTaylorPanel161_3.certificate, FiniteLowTaylorPanel161_6.certificate, FiniteLowTaylorPanel161_7.certificate,
  FiniteLowTaylorPanel161_13.certificate, FiniteLowTaylorPanel161_14.certificate, FiniteLowTaylorPanel162_2.certificate, FiniteLowTaylorPanel162_3.certificate, FiniteLowTaylorPanel162_11.certificate,
  FiniteLowTaylorPanel162_12.certificate, FiniteLowTaylorPanel162_17.certificate, FiniteLowTaylorPanel162_18.certificate, FiniteLowTaylorPanel163_2.certificate, FiniteLowTaylorPanel163_3.certificate,
  FiniteLowTaylorPanel163_11.certificate, FiniteLowTaylorPanel163_12.certificate, FiniteLowTaylorPanel163_17.certificate, FiniteLowTaylorPanel163_18.certificate, FiniteLowTaylorPanel164_2.certificate,
  FiniteLowTaylorPanel164_3.certificate, FiniteLowTaylorPanel164_10.certificate, FiniteLowTaylorPanel164_11.certificate, FiniteLowTaylorPanel164_20.certificate, FiniteLowTaylorPanel164_21.certificate,
  FiniteLowTaylorPanel165_4.certificate, FiniteLowTaylorPanel165_5.certificate, FiniteLowTaylorPanel165_11.certificate, FiniteLowTaylorPanel165_12.certificate, FiniteLowTaylorPanel165_21.certificate,
  FiniteLowTaylorPanel165_22.certificate, FiniteLowTaylorPanel166_3.certificate, FiniteLowTaylorPanel166_5.certificate, FiniteLowTaylorPanel166_6.certificate, FiniteLowTaylorPanel166_11.certificate,
  FiniteLowTaylorPanel166_12.certificate, FiniteLowTaylorPanel166_15.certificate, FiniteLowTaylorPanel166_16.certificate, FiniteLowTaylorPanel167_3.certificate, FiniteLowTaylorPanel167_8.certificate,
  FiniteLowTaylorPanel167_9.certificate, FiniteLowTaylorPanel167_12.certificate, FiniteLowTaylorPanel167_13.certificate, FiniteLowTaylorPanel167_16.certificate, FiniteLowTaylorPanel167_17.certificate,
  FiniteLowTaylorPanel168_5.certificate, FiniteLowTaylorPanel168_10.certificate, FiniteLowTaylorPanel168_11.certificate, FiniteLowTaylorPanel168_15.certificate, FiniteLowTaylorPanel168_16.certificate,
  FiniteLowTaylorPanel168_20.certificate, FiniteLowTaylorPanel168_21.certificate, FiniteLowTaylorPanel169_5.certificate, FiniteLowTaylorPanel169_6.certificate, FiniteLowTaylorPanel169_11.certificate,
  FiniteLowTaylorPanel169_12.certificate, FiniteLowTaylorPanel169_17.certificate, FiniteLowTaylorPanel169_18.certificate, FiniteLowTaylorPanel170_5.certificate, FiniteLowTaylorPanel170_6.certificate,
  FiniteLowTaylorPanel170_11.certificate, FiniteLowTaylorPanel170_12.certificate, FiniteLowTaylorPanel170_18.certificate, FiniteLowTaylorPanel170_19.certificate, FiniteLowTaylorPanel171_3.certificate,
  FiniteLowTaylorPanel171_4.certificate, FiniteLowTaylorPanel171_5.certificate, FiniteLowTaylorPanel171_13.certificate, FiniteLowTaylorPanel171_14.certificate, FiniteLowTaylorPanel172_3.certificate,
  FiniteLowTaylorPanel172_4.certificate, FiniteLowTaylorPanel172_5.certificate, FiniteLowTaylorPanel172_13.certificate, FiniteLowTaylorPanel172_14.certificate, FiniteLowTaylorPanel173_2.certificate,
  FiniteLowTaylorPanel173_5.certificate, FiniteLowTaylorPanel173_6.certificate, FiniteLowTaylorPanel173_13.certificate, FiniteLowTaylorPanel173_14.certificate, FiniteLowTaylorPanel173_21.certificate,
  FiniteLowTaylorPanel173_22.certificate
]

theorem allPanels_size : allPanels.size = 1101 := by decide +kernel

theorem allPanels_sound (i : Fin allPanels.size) {μ : ProbabilityMeasure ℝ}
    (hμ : Admissible μ) {n : ℕ} (hn : (allPanels[i]).samples ≤ n)
    (hnH : n ≤ (allPanels[i]).samplesUpper)
    (hβ : thirdAbsMoment μ ≤ (allPanels[i]).beta) :
    (∫ s in ((allPanels[i]).left : ℝ)..(allPanels[i]).right,
      prawitzLowError (normalizedSumLaw μ n)
        (((allPanels[i]).cutoff : ℝ) * sqrt n) s) ≤
      (allPanels[i]).upper := (allPanels[i]).bound hμ hn hnH hβ

end FiniteLowTaylorPanels
